apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
  namespace: slackishapp
spec:
  serviceName: mysql
  template:
    metadata:
      labels:
        name: mysql
      namespace: slackishapp
    spec:
      containers:
        - name: container-mysql
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: evensecreter
            - name: MYSQL_DATABASE
              value: slacksishdb
            - name: MYSQL_USER
              value: slacksishdbuser
            - name: MYSQL_PASSWORD
              value: supersecret
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
