apiVersion: v1
kind: Service
metadata:
  name: slackish-webapp-service
  labels:
    app: slackish-webapp
  namespace: slackishapp
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30080
  selector:
    app: slackish-webapp
